### ISSUE TITLE
Clustering and Marker Gene Identification: SC3 vs Seurat

### ISSUE THREAD

**Issue by igordot** [hemberg-lab/scRNA.seq.course#151]
In section 10.4, you have the following notes:

> Clustering and Marker Gene Identification
> - &le; 5000 cells : SC3
> - &gt; 5000 cells : Seurat

I haven't seen that elsewhere. Is there a specific reason for the difference?

**Comment by mhemberg** [comment]
SC3 scales poorly with the number of cells in your sample and after 5k cells it is quite slow and requires significant amounts of memories. Seurat is significantly faster, but according to our benchmarks it is less accurate for small datasets. If you have a fast machine or little patience you may want to adjust the recommended threshold.

**Comment by tallulandrews** [comment]
Some of the benchmarks are available in the SC3 paper, see: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5410170/ 
Though Seurat has been updated a few times since then, but our piecemeal checking of the above on newer versions suggest the updates haven't radically improved its performance on small datasets.
