### ISSUE TITLE
"trim_galore" command could not be found

### ISSUE THREAD

**Issue by zzygyx9119** [hemberg-lab/scRNA.seq.course#166]
I am trying to follow the tutorials in RStudio. In "process-raw-QC.Rmd", when I run the following command, it said that trim_galore could not be found.  I redownloaded the image, but still got the problem. Could you please let me know how to solve this? Should I try earlier version of this class? Thank you!

`
```{bash, eval=FALSE}
trim_galore -h
```
`
> /tmp/RtmpgcO0S6/chunk-code-2e2786f67e.txt: line 1: trim_galore: command not found

Jeff

**Comment by zzygyx9119** [comment]
Sorry, I forgot to mention that I am using the latest version v4.11.

**Comment by zzygyx9119** [comment]
I solved this issue. Basically, go to folder /usr/local/bin, recreate the link "sudo ln -s /opt/TrimGalore/TrimGalore-0.4.5/trim_galore ." . Hopefully this is helpful to others.

Jeff

**Comment by zcle** [comment]
Hi,
I also encounter the same question. While I am using the windows platform. Do you have any suggestions for this? Thanks!

**Comment by zcle** [comment]
Did something similar to what zzygyx9119 mentioned, I also solved the issue. Since I use docker in Windows, I open the docker CLI (something like terminal), and I go to folder /usr/local/bin, delete trim_galore and then recreate the link by "sudo ln -s /opt/TrimGalore/TrimGalore-0.4.5/trim_galore trim_galore". Then it is ok
