### ISSUE TITLE
Incompatibilities between R and R studio

### ISSUE THREAD

**Issue by royassis** [hemberg-lab/scRNA.seq.course#183]
Hey 

I'm trying to go over the course, and going over this link:
https://www.singlecellcourse.org/introduction-to-rbioconductor.html#basic-data-structures

I'm getting a warning.
```
reds = c("red", rgb(1,0,0), hsv(0, 1, 1))
Warning message:
R graphics engine version 14 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
```

<img width="1902" alt="viz_issue" src="https://user-images.githubusercontent.com/34189329/148765755-8f76475b-58fc-4fde-9a48-dda0306fb85b.PNG">

**Comment by prete** [comment]
Fixed in the latest container version `quay.io/cellgeni/scrna-seq-course:latest` that has:
- R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
- RStudio 2022.07.0+548 (Spotted Wakerobin) for Ubuntu Bionic

https://github.com/cellgeni/scRNA.seq.course/commit/4bfafae9b8e3417c63d5aeda5d460f5a20409d24
