### ISSUE TITLE
log transform blishak data after normalisations!

### ISSUE THREAD

**Issue by wikiselev** [hemberg-lab/scRNA.seq.course#72]
in the normalisation chapter we sometimes forget to logtransform the data after doing normalisations

**Comment by wikiselev** [comment]
Looks like there is no `log-transform` parameter in the plotPCA() function, so we won't be able to easily create a PCA plot of a given scater object slot...

Davis, is there any way of implementing this functionality?

**Comment by davismcc** [comment]
Shouldn't we just make sure we log-transform the data before doing PCA? PCA on count data is not a great idea.

**Comment by wikiselev** [comment]
Ok, but how do we do that in a simple way? If we use expression values, they will be not just log-transformed but also cpm-ed?

**Comment by davismcc** [comment]
Yes, in scater the `exprs` values will be cpm'd as well as log-transformed. For every setting, as far as I can see, apart from paedagogical discussions, the `exprs` values should be log2(cpm) - it would never make sense in an actual analyses to use log2(counts) or similar, since you will have differences between cells driven by completely technical factors like sequencing depth.

For the sake of the course, if you want to demonstrate what PCA on log2-counts looks like, then we could do:
```
set_exprs(sce, "log2_counts") <- log2(counts(sce) + 1)
plotPCA(sce, exprs_values = "log2_counts")
```

We should make the point in the course that this is not something that you would ever want to do in practice, but can show it to demonstrate what's going on.

That said, if we're doing PCA on log2-counts to make a point, then we could just as well do PCA on counts, with the caveat that this is "not something you should try at home".

For *actual* visualizations in analysis, the expression values used need to account for differences in sequencing depth to make cells at all comparable, so cpm/tpm/fpkm are required, and log-transforming them makes most sense.

**Comment by wikiselev** [comment]
Great, thanks for that Davis! I've implemented your suggested scenario:
```
set_exprs(sce, "log2_counts") <- log2(counts(sce) + 1)
plotPCA(sce, exprs_values = "log2_counts")
```
Building it now, hopefully the build will not FAIL :-) But at least we will be doing something reasonable, what we've had so far (raw counts everywhere) was really not ideal!

**Comment by wikiselev** [comment]
My logic is - we shouldn't use cpm before the normalisation step, that is why I decided to go for `log2_counts`.

**Comment by davismcc** [comment]
OK, that sounds good to me. I agree that in the context of the course, makes sense to build up counts --> cpm --> further normalisation. We can say in discussion that in a real analysis it makes most sense to go straight to log2(cpm) for visualization, and from there assess further downstream normalization approaches.

**Comment by wikiselev** [comment]
Yes, I've added a comment just after we introduce `log2_counts` (it's not live yet). BTW, the builds was ok, so the new PCAs are already online. Thanks again for your help, Davis!
